#include "../fattn-vec.cuh"

#define DECL_FATTN_VEC_TQKV_CASES(type) \
DECL_FATTN_VEC_CASE( 64, type, type);   \
DECL_FATTN_VEC_CASE(128, type, type);   \
DECL_FATTN_VEC_CASE(256, type, type);   \

DECL_FATTN_VEC_TQKV_CASES(GGML_TYPE_TQKV_2_0)
DECL_FATTN_VEC_TQKV_CASES(GGML_TYPE_TQKV_2_5)
DECL_FATTN_VEC_TQKV_CASES(GGML_TYPE_TQKV_3_0)
DECL_FATTN_VEC_TQKV_CASES(GGML_TYPE_TQKV_3_5)
DECL_FATTN_VEC_TQKV_CASES(GGML_TYPE_TQKV_4_0)
DECL_FATTN_VEC_TQKV_CASES(GGML_TYPE_TQKV_2_0_IP)
DECL_FATTN_VEC_TQKV_CASES(GGML_TYPE_TQKV_2_5_IP)
DECL_FATTN_VEC_TQKV_CASES(GGML_TYPE_TQKV_3_0_IP)
DECL_FATTN_VEC_TQKV_CASES(GGML_TYPE_TQKV_3_5_IP)
DECL_FATTN_VEC_TQKV_CASES(GGML_TYPE_TQKV_4_0_IP)

#undef DECL_FATTN_VEC_TQKV_CASES
